service:
    name: hello-world

provider:
  name: cloudflare
  config:
    accountId: ACCOUNT_ID
    zoneId: ZONE_ID

plugins:
  - serverless-cloudflare-workers

functions:
  get-hues:
    name: get-hues
    script: get-hues
    webpack: true
    resources:
      kv:
        - variable: HUES
          namespace: hues
    events:
      - http:
          url: example.com/get-hues
          method: GET
  add-hue:
    name: add-hue
    script: add-hue
    webpack: true
    resources:
      kv:
        - variable: HUES
          namespace: hues
    events:
      - http:
          url: example.com/add-hue
          method: POST
